[project]
name = "basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zain-The-Coder", email = "zain015976@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.28.0",
    "langchain>=1.3.16",
    "langchain-huggingface>=1.2.2",
]

[project.scripts]
basics = "basics:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
